### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SliverStaggeredGrid'.  : SliverStaggeredGrid.countBuilder(

### ISSUE THREAD

**Issue by arafat1971** [taydinadnan/BringApp-Delivery-service-app#3]
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SliverStaggeredGrid'.
                    : SliverStaggeredGrid.countBuilder(

quick fix messages are ( Undefined name 'SliverStaggeredGrid'.
Try correcting the name to one that is defined, or defining the name )

**Comment by taydinadnan** [comment]
I hope you're doing well!

I wanted to share that I’m currently building an updated and functional
version of the BringApp food vendor clone app, and I’m documenting each
step in a guide on Medium. This series walks through the entire development
process, from initial setup to advanced features, so anyone interested can
follow along.

The first post, titled "Building an Updated BringApp Food Vendor Clone App
with Flutter – Part 1: Seller App Setup,"
***@***.***/building-an-updated-bringapp-food-vendor-clone-app-with-flutter-1-seller-app-setup-796607d0f0d1>
is already live, and I’ll be publishing additional parts soon to complete
the series.

Feel free to check it out, and let me know if you have any questions or
feedback!

Arafat ***@***.***>, 5 Ağu 2022 Cum, 16:21 tarihinde şunu
yazdı:
