### ISSUE TITLE
instructions on how to run this?

### ISSUE THREAD

**Issue by 43v3rn88b** [taydinadnan/BringApp-Delivery-service-app#7]

**Comment by PanwalaVandan** [comment]
HI @taydinadnan ,

Appreciate your help on how to run this live or how to setup this system?

Thanks

**Comment by taydinadnan** [comment]
I hope you're doing well!

I wanted to share that I’m currently building an updated and functional
version of the BringApp food vendor clone app, and I’m documenting each
step in a guide on Medium. This series walks through the entire development
process, from initial setup to advanced features, so anyone interested can
follow along.

The first post, titled "Building an Updated BringApp Food Vendor Clone App
with Flutter – Part 1: Seller App Setup,"
***@***.***/building-an-updated-bringapp-food-vendor-clone-app-with-flutter-1-seller-app-setup-796607d0f0d1>
is already live, and I’ll be publishing additional parts soon to complete
the series.

Feel free to check it out, and let me know if you have any questions or
feedback!

PanwalaVandan ***@***.***>, 31 Mar 2023 Cum, 15:34 tarihinde
şunu yazdı:
